apiVersion: v1
kind: Service
metadata:
  name: microservicio-registro
spec:
  selector:
    app: microservicio-registro
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
  type: LoadBalancer